### ISSUE TITLE
Gilles didn't drop his quill again

### ISSUE THREAD

**Issue by mautschi** [b5635/the-frozen-north#334] opened 2021-05-23 07:50 UTC

**Comment by b5635** [comment] 2021-05-24 01:42
Hmm, I'm looking at the quest variables but they look alright. I'll give it a whirl myself and report back. If Gilles doesn't drop any loot at all, I might know what the issue is.

**Comment by mautschi** [comment] 2021-05-24 07:14
IIRC there was no loot bag from him, yes

**Comment by b5635** [comment] 2022-07-12 07:09
I don't see any reports on this, closing for now.

**Closed by b5635** 2022-07-12 07:09 UTC
