### ISSUE TITLE
found a +3 weapon on Leorio / a bullet fabricator +3 PROBABLY on a False Helmite (Leorio was there, too but it was a huge crowd) at Lvl 6. Party size: just my PC

### ISSUE THREAD

**Issue by mautschi** [b5635/the-frozen-north#327] opened 2021-05-22 09:27 UTC
![20210522112416_1](https://user-images.githubusercontent.com/83913954/119221676-f40e8e00-badf-11eb-8d95-ed5730d42172.jpg)

**Comment by mautschi** [comment] 2021-05-22 14:37
![20210522163515_1](https://user-images.githubusercontent.com/83913954/119230312-2aadce00-bb0b-11eb-882d-a0ad1a82c91f.jpg)

**Comment by tinygiant98** [comment] 2021-05-22 18:22
T5 weapons can be found on CR5 bosses and greater, with an extremely low probability. Will need to change the CR bonus logic to prevent this if it's not intended behavior.

**Comment by b5635** [comment] 2021-05-22 18:37
Should be fixed now

**Closed by b5635** 2021-05-22 18:37 UTC
